### ISSUE TITLE
Add country code to the name of the league in soccer dataset

### ISSUE THREAD

**Issue by katush** [thinkh/lineup_app#1]
Add country code to the name of the league in soccer dataset:

* NLD - Eredivisie
* BEL - Jupiler Pro League
* ESP - LaLiga
* PRT - Liga NOS
* FRA - Ligue 1
* GBR - Premier League
* RUS - Premier Liga
* ITA - Serie A
* GRC - Super League
* TUR - Süper Lig

**Comment by thinkh** [comment]
Done with 63796c6
